### PR TITLE
Group fixes

### LINKED ISSUE #80: Make finding the group a parameter is in more efficient for encoding and decoding
Right now the code must generate what params are in a group and how long they are each time they are encoded and decoded. It would be more efficient to store that information in static memory with the group

### LINKED ISSUE #83: Issue when encoding and decoding negative float datatypes
If a float gets encoded to a value below zero, it just gets truncated to 0 when it is cased to a U64. This is an issue as the MoTeC ECU frequently sends negative values that are stored in the library as a float, usually as a S16 on the bus with some scaler. A potential solution would be to read off the bus as a S16 and convert that to a float

### PR DESCRIPTION
**Pull request by olale013**
* Simplifies parameter group construction
* Migrated to CMSIS v1
* Forces integer math when encoding/decoding parameters to avoid loss of precision with floats.
  * If an integer parameter is configured with a scale between 0 and 1, the value is truncated to 0. In this case, scale = 1 is used to avoid dividing by 0.
* Floats are sent as signed values

Fixes #80
Fixes #83

### CODE REVIEW

File: network_autogen/templates/GopherCAN_network.c.jinja2 [hunk 1]
```diff
@@ -22,6 +22,7 @@ CAN_INFO_STRUCT empty_param = {0};
         .TYPE = {{ param.type }},
         .SIZE = {{ param.type }}_SIZE,
         .ENC = {{ param.encoding }},
+        .ENC_SIZE = {{ param.length }},
```
Comment (caljay98) [inline network_autogen/templates/GopherCAN_network.c.jinja2:25]: Just had a thought, what if we also gave an array in each group called .param_len that stores the encoding length of each parameter in each slot. The we could retain the functionality of being able to send parameters in different ways

File: GopherCAN.c [hunk 2]
```diff
@@ -508,44 +490,38 @@ static S8 decode_parameter(CAN_INFO_STRUCT* param, U8* data, U8 start, U8 length
...
             break;
         case FLOATING:
-            value_fl = ((float) value * param->SCALE) + param->OFFSET;
-            ((FLOAT_CAN_STRUCT*) param)->data = value_fl;
+            // floats are signed values in data frame
+            if (length == 1) value_fl = (S8)value;
+            else if (length == 2) value_fl = (S16)value;
+            else if (length == 4) value_fl = (S32)value;
+            else if (length == 8) value_fl = (S64)value;
+            ((FLOAT_CAN_STRUCT*)param)->data = (value_fl * param->SCALE) + param->OFFSET;
```
Comment (caljay98) [inline GopherCAN.c:525]: I think there should be one more 'else' that just decodes it as a U64 like before just in case something is not configured correctly

**Review by caljay98 — CHANGES_REQUESTED** [review]
Looks good. Biggest thing is an idea I had with storing the lengths in the groups to keep the functionality of sending parameters with different sizes on the bus for different precision. Interested to hear your thoughts

File: network_autogen/templates/GopherCAN_network.c.jinja2 (hunk 1 above)
Comment (olale013) [reply network_autogen/templates/GopherCAN_network.c.jinja2:25]: This is what I was suggesting earlier lol. If we want params to be in multiple groups though, we need a way to determine which one to send when you call send_parameter.

Comment (caljay98) [reply network_autogen/templates/GopherCAN_network.c.jinja2:25]: I am an idiot it seems, I forgot about that whole conversation. This solution is good then

**Review by caljay98 — APPROVED** [review]
